version: '3'

services:
  swagger_ui:
    image: swaggerapi/swagger-ui:v3.20.1
    volumes:
      - ./swagger/magento2.json:/opt/app/magento2.json
    environment:
      - SWAGGER_JSON=/opt/app/magento2.json
    ports:
      - 80:8080