version: '3'

services:
  nginx:
    image: nginx:1.15.7-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./swagger/magento2.json:/opt/app/magento2.json
    entrypoint: nginx -g "daemon off;"
    ports:
      - 8080:80
  swagger_ui:
    image: swaggerapi/swagger-ui:v3.20.1
    environment:
      - API_URL=http://127.0.0.1:8080/magento2.json
    ports:
      - 80:8080